### ISSUE TITLE
Docket sheets popover has some messy flow 

### ISSUE THREAD

**Issue by niharikasingh** [knod/docassemble-juvenilesealing#48] opened 2020-01-23 01:52 UTC
This is a two part bug manifesting as weird flow when the user clicks on the popover. Repro steps: 

1. Get to the "Do you have certified copies of your docket sheets question?" (Eligibility question 2)
2. Click on the "docket sheets" popover
3. Click on the link inside the popover 
4. [BUG 1] Both the "yes" and the "no" button lead to the same place. Click either one. 
5. Click "No" for the question "Do you have certified copies of your docket sheets question?"
6. [BUG 2] The screen that you now see will be based on whether you clicked yes or no in step 4, when it should be the `wants_dockets_now` sheet regardless of what you clicked

**Comment by knod** [comment] 2020-01-23 14:09
Is it worth breaking the two-page flow out into its own block where we always force the two-step process with `force_ask`?

**Comment by knod** [comment] 2020-02-27 13:21
Oh, is #56 a duplicate of this issue?

**Comment by niharikasingh** [comment] 2020-02-27 20:48
@knod I think #56 is a duplicate of [BUG 1] above.

**Comment by knod** [comment] 2020-03-08 13:33
Maybe it's better to have an issue for each anyway.

**Comment by knod** [comment] 2020-03-08 13:37
Step 6 says "it should be the `wants_dockets_now` sheet regardless of what you clicked." I'm not sure that's true. Proposed path: If you say you want to continue with the form, you should be allowed to go on to the next interview question, not go to the instructions for getting docket sheets. Thoughts?

**Comment by knod** [comment] 2020-03-09 13:15
"regardless of what you clicked" _in step 4_. I get it now. Makes sense.

**Closed** 2020-03-25 11:47 UTC
Labels: bug
