### ISSUE TITLE
finish by hand UI tests 

### ISSUE THREAD

**Issue by sperrys** [knod/docassemble-juvenilesealing#49] opened 2020-01-23 03:45 UTC
aloe test that asserts on the user flow after a user elects to finish the form by hand

After I am found to be eligible, if I click the "Finish by hand" button,
 I should be taken to the correct page.
 If I click continue on that page, I should be taken to the final page.

**Comment by knod** [comment] 2020-02-25 14:09
First described in #29. Perhaps that information should be moved into here.

**Comment by niharikasingh** [comment] 2020-02-25 14:45
Closing because duplicate of #29. I copied the relevant information there :)

**Closed by niharikasingh** 2020-02-25 14:45 UTC
